In [2]:
import pandas as pd
import numpy as np

np.random.seed(42)

N_SOCIOS = 4000
FECHA_INICIO = "2023-01-01"
FECHA_FIN = "2025-12-31"

In [5]:
dim_centro = pd.DataFrame({
    "id_centro": [1, 2, 3],
    "nombre_centro": ["Malasaña", "Vallecas", "Carabanchel"],
    "barrio": ["Malasaña", "Vallecas", "Carabanchel"],
    "tipo_zona": ["centrica", "residencial", "mixta"],
    "capacidad_socios": [850, 1100, 950],
    "precio_base_mensual": [45.0, 35.0, 39.0]
})

dim_centro

,id_centro,nombre_centro,barrio,tipo_zona,capacidad_socios,precio_base_mensual
0,1,Malasaña,Malasaña,centrica,850,45.0
1,2,Vallecas,Vallecas,residencial,1100,35.0
2,3,Carabanchel,Carabanchel,mixta,950,39.0

In [3]:
dim_contrato = pd.DataFrame({
    "id_contrato": [1, 2, 3],
    "tipo_contrato": ["mensual", "semestral", "anual"],
    "duracion_meses": [1, 6, 12],
    "cuota_mensual": [45.0, 40.0, 35.0]
})

dim_contrato

   id_contrato tipo_contrato  duracion_meses  cuota_mensual
0            1       mensual               1           45.0
1            2     semestral               6           40.0
2            3         anual              12           35.0

In [4]:
dim_canal_captacion = pd.DataFrame({
    "id_canal": [1, 2, 3, 4],
    "canal_captacion": [
        "redes_sociales",
        "recomendacion",
        "publicidad",
        "paso_calle"
    ],
    "coste_captacion": [60, 20, 45, 10],
    "calidad_esperada": [
        "media",
        "alta",
        "media_baja",
        "baja"
    ]
})

dim_canal_captacion

   id_canal canal_captacion  coste_captacion calidad_esperada
0         1  redes_sociales               60            media
1         2   recomendacion               20             alta
2         3      publicidad               45       media_baja
3         4      paso_calle               10             baja

In [5]:
fechas = pd.date_range(
    start=FECHA_INICIO,
    end=FECHA_FIN,
    freq="D"
)

dim_fecha = pd.DataFrame({
    "fecha": fechas
})

dim_fecha.head()

       fecha
0 2023-01-01
1 2023-01-02
2 2023-01-03
3 2023-01-04
4 2023-01-05

In [6]:
dim_fecha.shape

(1096, 1)

In [7]:
dim_fecha["id_fecha"] = dim_fecha["fecha"].dt.strftime("%Y%m%d").astype(int)

dim_fecha["año"] = dim_fecha["fecha"].dt.year

dim_fecha["mes"] = dim_fecha["fecha"].dt.month

dim_fecha["trimestre"] = "Q" + dim_fecha["fecha"].dt.quarter.astype(str)

dim_fecha.head()

       fecha  id_fecha   año  mes trimestre
0 2023-01-01  20230101  2023    1        Q1
1 2023-01-02  20230102  2023    1        Q1
2 2023-01-03  20230103  2023    1        Q1
3 2023-01-04  20230104  2023    1        Q1
4 2023-01-05  20230105  2023    1        Q1

In [8]:
meses_es = {
    1: "enero",
    2: "febrero",
    3: "marzo",
    4: "abril",
    5: "mayo",
    6: "junio",
    7: "julio",
    8: "agosto",
    9: "septiembre",
    10: "octubre",
    11: "noviembre",
    12: "diciembre"
}

dim_fecha["nombre_mes"] = dim_fecha["mes"].map(meses_es)

dim_fecha.head()

       fecha  id_fecha   año  mes trimestre nombre_mes
0 2023-01-01  20230101  2023    1        Q1      enero
1 2023-01-02  20230102  2023    1        Q1      enero
2 2023-01-03  20230103  2023    1        Q1      enero
3 2023-01-04  20230104  2023    1        Q1      enero
4 2023-01-05  20230105  2023    1        Q1      enero

In [9]:
def asignar_temporada(mes):
    if mes == 1:
        return "año_nuevo"
    elif mes in [2, 3]:
        return "abandono_post_enero"
    elif mes in [7, 8]:
        return "verano"
    elif mes == 9:
        return "vuelta_rutina"
    elif mes in [10, 11]:
        return "abandono_post_septiembre"
    else:
        return "normal"

dim_fecha["temporada"] = dim_fecha["mes"].apply(asignar_temporada)

dim_fecha.head()

       fecha  id_fecha   año  mes trimestre nombre_mes  temporada
0 2023-01-01  20230101  2023    1        Q1      enero  año_nuevo
1 2023-01-02  20230102  2023    1        Q1      enero  año_nuevo
2 2023-01-03  20230103  2023    1        Q1      enero  año_nuevo
3 2023-01-04  20230104  2023    1        Q1      enero  año_nuevo
4 2023-01-05  20230105  2023    1        Q1      enero  año_nuevo

In [10]:
dim_fecha.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1096 entries, 0 to 1095
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   fecha       1096 non-null   datetime64[ns]
 1   id_fecha    1096 non-null   int64
 2   año         1096 non-null   int32
 3   mes         1096 non-null   int32
 4   trimestre   1096 non-null   object
 5   nombre_mes  1096 non-null   object
 6   temporada   1096 non-null   object
dtypes: datetime64[ns](1), int32(2), int64(1), object(3)
memory usage: 51.5+ KB

In [13]:
dim_fecha.sample(5)

,fecha,id_fecha,año,mes,trimestre,nombre_mes,temporada
139,2023-05-20,20230520,2023,5,Q2,mayo,normal
864,2025-05-14,20250514,2025,5,Q2,mayo,normal
291,2023-10-19,20231019,2023,10,Q4,octubre,abandono_post_septiembre
796,2025-03-07,20250307,2025,3,Q1,marzo,abandono_post_enero
599,2024-08-22,20240822,2024,8,Q3,agosto,verano

In [14]:
dim_fecha.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1096 entries, 0 to 1095
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   fecha       1096 non-null   datetime64[ns]
 1   id_fecha    1096 non-null   int64
 2   año         1096 non-null   int32
 3   mes         1096 non-null   int32
 4   trimestre   1096 non-null   object
 5   nombre_mes  1096 non-null   object
 6   temporada   1096 non-null   object
dtypes: datetime64[ns](1), int32(2), int64(1), object(3)
memory usage: 51.5+ KB

In [15]:
dim_fecha.sample(5)

         fecha  id_fecha   año  mes trimestre nombre_mes            temporada
969 2025-08-27  20250827  2025    8        Q3     agosto               verano
17  2023-01-18  20230118  2023    1        Q1      enero            año_nuevo
129 2023-05-10  20230510  2023    5        Q2       mayo               normal
585 2024-08-08  20240808  2024    8        Q3     agosto               verano
41  2023-02-11  20230211  2023    2        Q1    febrero  abandono_post_enero

In [16]:
dim_socios = pd.DataFrame({
    "id_socio": range(1, N_SOCIOS + 1),
    
    "genero": np.random.choice(
        ["Hombre", "Mujer"],
        size=N_SOCIOS,
        p=[0.55, 0.45]
    ),
    
    "vive_cerca": np.random.choice(
        [0, 1],
        size=N_SOCIOS,
        p=[0.30, 0.70]
    ),
    
    "tiene_pareja_socio": np.random.choice(
        [0, 1],
        size=N_SOCIOS,
        p=[0.85, 0.15]
    ),
    
    "telefono_registrado": np.random.choice(
        [0, 1],
        size=N_SOCIOS,
        p=[0.05, 0.95]
    ),
    
    "id_centro": np.random.choice(
        [1, 2, 3],
        size=N_SOCIOS,
        p=[0.25, 0.40, 0.35]
    ),
    
    "id_contrato": np.random.choice(
        [1, 2, 3],
        size=N_SOCIOS,
        p=[0.60, 0.25, 0.15]
    ),
    
    "id_canal": np.random.choice(
        [1, 2, 3, 4],
        size=N_SOCIOS,
        p=[0.35, 0.30, 0.20, 0.15]
    )
})

dim_socios.head()

,id_socio,genero,vive_cerca,tiene_pareja_socio,telefono_registrado,id_centro,id_contrato,id_canal
0,1,Hombre,1,0,1,1,1,4
1,2,Mujer,0,0,1,1,3,3
2,3,Hombre,1,0,1,2,1,1
3,4,Mujer,1,0,1,2,1,2
4,5,Mujer,1,0,1,3,1,2

In [17]:
dim_socios.shape

(4000, 8)

In [18]:
print("Distribución género:")
print(dim_socios["genero"].value_counts(normalize=True).round(2))

print("\nDistribución vive cerca:")
print(dim_socios["vive_cerca"].value_counts(normalize=True).round(2))

print("\nDistribución pareja socio:")
print(dim_socios["tiene_pareja_socio"].value_counts(normalize=True).round(2))

print("\nDistribución centro:")
print(dim_socios["id_centro"].value_counts(normalize=True).round(2))

print("\nDistribución contrato:")
print(dim_socios["id_contrato"].value_counts(normalize=True).round(2))

print("\nDistribución canal:")
print(dim_socios["id_canal"].value_counts(normalize=True).round(2))

Distribución género:
genero
Hombre    0.56
Mujer     0.44
Name: proportion, dtype: float64

Distribución vive cerca:
vive_cerca
1    0.7
0    0.3
Name: proportion, dtype: float64

Distribución pareja socio:
tiene_pareja_socio
0    0.84
1    0.16
Name: proportion, dtype: float64

Distribución centro:
id_centro
2    0.39
3    0.37
1    0.24
Name: proportion, dtype: float64

Distribución contrato:
id_contrato
1    0.60
2    0.25
3    0.15
Name: proportion, dtype: float64

Distribución canal:
id_canal
1    0.36
2    0.30
3    0.20
4    0.14
Name: proportion, dtype: float64

In [19]:
def generar_edad(id_centro):
    if id_centro == 1:      # Malasaña
        edad = np.random.normal(loc=30, scale=6)
    elif id_centro == 2:    # Vallecas
        edad = np.random.normal(loc=42, scale=8)
    else:                   # Carabanchel
        edad = np.random.normal(loc=38, scale=7)
    
    return int(np.clip(round(edad), 18, 75))


dim_socios["edad"] = dim_socios["id_centro"].apply(generar_edad)

dim_socios.head()

,id_socio,genero,vive_cerca,tiene_pareja_socio,telefono_registrado,id_centro,id_contrato,id_canal,edad
0,1,Hombre,1,0,1,1,1,4,26
1,2,Mujer,0,0,1,1,3,3,31
2,3,Hombre,1,0,1,2,1,1,39
3,4,Mujer,1,0,1,2,1,2,45
4,5,Mujer,1,0,1,3,1,2,38

In [20]:
dim_socios.groupby("id_centro")["edad"].agg(
    ["count", "min", "max", "mean"]
).round(1)

           count  min  max  mean
id_centro
1            946   18   49  30.0
2           1572   18   67  41.9
3           1482   18   59  38.2

In [22]:
def generar_fecha_alta():
    año = np.random.choice([2023, 2024, 2025], p=[0.34, 0.33, 0.33])
    
    mes = np.random.choice(
        range(1, 13),
        p=[
            0.18,  # enero
            0.10,  # febrero
            0.08,  # marzo
            0.07,  # abril
            0.07,  # mayo
            0.06,  # junio
            0.04,  # julio
            0.02,  # agosto
            0.14,  # septiembre
            0.09,  # octubre
            0.08,  # noviembre
            0.07   # diciembre
        ]
    )
    
    dia = np.random.randint(1, 29)
    
    return pd.Timestamp(year=año, month=mes, day=dia)


dim_socios["fecha_alta"] = [generar_fecha_alta() for _ in range(N_SOCIOS)]

dim_socios.head()

,id_socio,genero,vive_cerca,tiene_pareja_socio,telefono_registrado,id_centro,id_contrato,id_canal,edad,fecha_alta
0,1,Hombre,1,0,1,1,1,4,26,2024-01-21
1,2,Mujer,0,0,1,1,3,3,31,2025-05-02
2,3,Hombre,1,0,1,2,1,1,39,2024-01-06
3,4,Mujer,1,0,1,2,1,2,45,2025-02-28
4,5,Mujer,1,0,1,3,1,2,38,2023-01-07

In [23]:
dim_socios["fecha_alta"].dt.month.value_counts().sort_index()

fecha_alta
1     724
2     389
3     342
4     270
5     298
6     240
7     152
8      79
9     532
10    388
11    320
12    266
Name: count, dtype: int64

In [24]:
(
    dim_socios["fecha_alta"]
    .dt.month
    .value_counts(normalize=True)
    .sort_index()
    .round(3)
)

fecha_alta
1     0.181
2     0.097
3     0.086
4     0.068
5     0.074
6     0.060
7     0.038
8     0.020
9     0.133
10    0.097
11    0.080
12    0.066
Name: proportion, dtype: float64

In [25]:
dim_socios["churn_final"] = np.random.choice(
    [0, 1],
    size=N_SOCIOS,
    p=[0.60, 0.40]
)

dim_socios["churn_final"].value_counts(normalize=True)

churn_final
0    0.6065
1    0.3935
Name: proportion, dtype: float64

In [27]:
dim_socios["riesgo_churn"] = 0

In [28]:
dim_socios.loc[
    dim_socios["id_contrato"] == 1,
    "riesgo_churn"
] += 3

dim_socios.loc[
    dim_socios["id_contrato"] == 2,
    "riesgo_churn"
] += 1

dim_socios.loc[
    dim_socios["id_contrato"] == 3,
    "riesgo_churn"
] -= 2

In [29]:
dim_socios.loc[
    dim_socios["vive_cerca"] == 0,
    "riesgo_churn"
] += 2

dim_socios.loc[
    dim_socios["vive_cerca"] == 1,
    "riesgo_churn"
] -= 1

In [30]:
dim_socios.loc[
    dim_socios["tiene_pareja_socio"] == 1,
    "riesgo_churn"
] -= 2

In [ ]:
dim_socios.loc[
    dim_socios["id_canal"] == 1,
    "riesgo_churn"
] += 1

dim_socios.loc[
    dim_socios["id_canal"] == 3,
    "riesgo_churn"
] += 1

dim_socios.loc[
    dim_socios["id_canal"] == 4,
    "riesgo_churn"
] += 2

dim_socios.loc[
    dim_socios["id_canal"] == 2,
    "riesgo_churn"
] -= 1

In [31]:
dim_socios["riesgo_churn"].describe()

count    4000.000000
mean        1.359500
std         2.357148
min        -5.000000
25%         0.000000
50%         2.000000
75%         2.000000
max         5.000000
Name: riesgo_churn, dtype: float64

In [32]:
dim_socios["riesgo_churn"].value_counts().sort_index()

riesgo_churn
-5      69
-3     342
-2     123
 0    1016
 1      47
 2    1417
 3     378
 5     608
Name: count, dtype: int64

In [33]:
riesgo_a_probabilidad = {
    -5: 0.05,
    -3: 0.10,
    -2: 0.15,
     0: 0.25,
     1: 0.35,
     2: 0.50,
     3: 0.70,
     5: 0.90
}

dim_socios["prob_churn"] = (
    dim_socios["riesgo_churn"]
    .map(riesgo_a_probabilidad)
)

In [34]:
dim_socios.head()

,id_socio,genero,vive_cerca,tiene_pareja_socio,telefono_registrado,id_centro,id_contrato,id_canal,edad,fecha_alta,churn_final,riesgo_churn,prob_churn
0,1,Hombre,1,0,1,1,1,4,26,2024-01-21,1,2,0.50
1,2,Mujer,0,0,1,1,3,3,31,2025-05-02,0,0,0.25
2,3,Hombre,1,0,1,2,1,1,39,2024-01-06,0,2,0.50
3,4,Mujer,1,0,1,2,1,2,45,2025-02-28,0,2,0.50
4,5,Mujer,1,0,1,3,1,2,38,2023-01-07,0,2,0.50

In [35]:
def generar_meses_activo(churn):
    
    if churn == 0:
        return np.nan
    
    return np.random.choice(
        [1, 2, 3, 4, 5, 6, 9, 12, 18, 24],
        p=[0.05, 0.08, 0.12, 0.15, 0.15,
           0.12, 0.10, 0.10, 0.08, 0.05]
    )

dim_socios["meses_activo"] = dim_socios["churn_final"].apply(
    generar_meses_activo
)

In [36]:
def calcular_fecha_baja(row):

    if row["churn_final"] == 0:
        return pd.NaT

    fecha_baja = (
        row["fecha_alta"] +
        pd.DateOffset(months=int(row["meses_activo"]))
    )

    if fecha_baja > pd.Timestamp(FECHA_FIN):
        return pd.NaT

    return fecha_baja


dim_socios["fecha_baja"] = dim_socios.apply(
    calcular_fecha_baja,
    axis=1
)

In [37]:
dim_socios[
    [
        "id_socio",
        "fecha_alta",
        "meses_activo",
        "fecha_baja",
        "churn_final"
    ]
].head(10)

   id_socio fecha_alta  meses_activo fecha_baja  churn_final
0         1 2024-01-21           1.0 2024-02-21            1
1         2 2025-05-02           NaN        NaT            0
2         3 2024-01-06           NaN        NaT            0
3         4 2025-02-28           NaN        NaT            0
4         5 2023-01-07           NaN        NaT            0
5         6 2024-02-18           NaN        NaT            0
6         7 2023-04-13           4.0 2023-08-13            1
7         8 2025-11-13           1.0 2025-12-13            1
8         9 2023-10-16           NaN        NaT            0
9        10 2025-01-07          18.0        NaT            1

In [38]:
dim_socios.shape

(4000, 15)

In [39]:
dim_socios["churn_final"].value_counts(normalize=True).round(3)

churn_final
0    0.606
1    0.394
Name: proportion, dtype: float64

In [40]:
dim_socios.groupby("id_centro")["edad"].agg(
    ["min","max","mean"]
).round(1)

           min  max  mean
id_centro
1           18   49  30.0
2           18   67  41.9
3           18   59  38.2

In [41]:
dim_socios["id_contrato"].value_counts(normalize=True).round(2)

id_contrato
1    0.60
2    0.25
3    0.15
Name: proportion, dtype: float64

In [42]:
dim_socios["id_canal"].value_counts(normalize=True).round(2)

id_canal
1    0.36
2    0.30
3    0.20
4    0.14
Name: proportion, dtype: float64

In [43]:
(
    dim_socios["fecha_alta"]
    .dt.month
    .value_counts(normalize=True)
    .sort_index()
    .round(3)
)

fecha_alta
1     0.181
2     0.097
3     0.086
4     0.068
5     0.074
6     0.060
7     0.038
8     0.020
9     0.133
10    0.097
11    0.080
12    0.066
Name: proportion, dtype: float64

In [44]:
(
    dim_socios["fecha_baja"] <
    dim_socios["fecha_alta"]
).sum()

np.int64(0)

In [45]:
dim_socios.isnull().sum()

id_socio                  0
genero                    0
vive_cerca                0
tiene_pareja_socio        0
telefono_registrado       0
id_centro                 0
id_contrato               0
id_canal                  0
edad                      0
fecha_alta                0
churn_final               0
riesgo_churn              0
prob_churn                0
meses_activo           2426
fecha_baja             2756
dtype: int64

In [47]:
dim_socios.groupby("id_contrato")["churn_final"].mean().round(3)

id_contrato
1    0.404
2    0.387
3    0.361
Name: churn_final, dtype: float64

In [48]:
dim_socios["churn_final"].value_counts(normalize=True).round(3)

churn_final
0    0.606
1    0.394
Name: proportion, dtype: float64

In [49]:
dim_socios.groupby(
    "vive_cerca"
)["churn_final"].mean().round(3)

vive_cerca
0    0.389
1    0.395
Name: churn_final, dtype: float64

In [50]:
dim_socios.groupby(
    "tiene_pareja_socio"
)["churn_final"].mean().round(3)

tiene_pareja_socio
0    0.393
1    0.394
Name: churn_final, dtype: float64

In [ ]:
# Borramos colimna de Riesgo de Churn, Probabilidad de Churn y Churn Final ya quue no se cumplian las proporciones esperadas de Churn Final
dim_socios = dim_socios.drop(
    columns=["riesgo_churn", "prob_churn", "churn_final"],
    errors="ignore"
)

In [53]:
#nueva columna de riesgo
dim_socios["riesgo_churn"] = 0

In [54]:
#Riesgo de churn por contrato
# Mensual
dim_socios.loc[
    dim_socios["id_contrato"] == 1,
    "riesgo_churn"
] += 3

# Semestral
dim_socios.loc[
    dim_socios["id_contrato"] == 2,
    "riesgo_churn"
] += 1

# Anual
dim_socios.loc[
    dim_socios["id_contrato"] == 3,
    "riesgo_churn"
] -= 2

In [55]:
# Riesgo de churn  vive cerca
# No vive cerca
dim_socios.loc[
    dim_socios["vive_cerca"] == 0,
    "riesgo_churn"
] += 3

# Vive cerca
dim_socios.loc[
    dim_socios["vive_cerca"] == 1,
    "riesgo_churn"
] -= 2

In [56]:
#Riesgo de churn por pareja socio
dim_socios.loc[
    dim_socios["tiene_pareja_socio"] == 1,
    "riesgo_churn"
] -= 3

In [57]:
# Riesgo de churn por canal de captación
# Redes sociales
dim_socios.loc[
    dim_socios["id_canal"] == 1,
    "riesgo_churn"
] += 1

# Recomendación
dim_socios.loc[
    dim_socios["id_canal"] == 2,
    "riesgo_churn"
] -= 2

# Publicidad
dim_socios.loc[
    dim_socios["id_canal"] == 3,
    "riesgo_churn"
] += 1

# Paso calle
dim_socios.loc[
    dim_socios["id_canal"] == 4,
    "riesgo_churn"
] += 3

In [59]:
# Riesgo de churn por edad
# 18-24
dim_socios.loc[
    dim_socios["edad"].between(18, 24),
    "riesgo_churn"
] += 3

# 25-35
dim_socios.loc[
    dim_socios["edad"].between(25, 35),
    "riesgo_churn"
] += 1

# 36-50
dim_socios.loc[
    dim_socios["edad"].between(36, 50),
    "riesgo_churn"
] -= 1

In [60]:
# Riesgo de churn por centro
# Malasaña
dim_socios.loc[
    dim_socios["id_centro"] == 1,
    "riesgo_churn"
] += 1

# Vallecas
dim_socios.loc[
    dim_socios["id_centro"] == 2,
    "riesgo_churn"
] -= 1

In [61]:
# Riesgo revisado
dim_socios["riesgo_churn"].describe()

count    4000.000000
mean        1.019750
std         4.569199
min       -12.000000
25%        -2.000000
50%         1.000000
75%         4.000000
max        16.000000
Name: riesgo_churn, dtype: float64

In [62]:
dim_socios["riesgo_churn"].value_counts().sort_index()

riesgo_churn
-12      3
-11      4
-10      3
-9      53
-8      37
-7      45
-6     145
-5     115
-4     256
-3     290
-2     202
-1     385
 0     384
 1     356
 2     329
 3     213
 4     255
 5     270
 6     164
 7     146
 8      83
 9     103
 10     74
 11     38
 12     18
 13      6
 14     17
 15      1
 16      5
Name: count, dtype: int64

In [63]:
def calcular_prob_churn(riesgo):

    if riesgo <= -5:
        return 0.05

    elif riesgo <= -1:
        return 0.15

    elif riesgo <= 3:
        return 0.35

    elif riesgo <= 7:
        return 0.60

    else:
        return 0.85


dim_socios["prob_churn"] = (
    dim_socios["riesgo_churn"]
    .apply(calcular_prob_churn)
)

In [64]:
dim_socios["prob_churn"].value_counts().sort_index()

prob_churn
0.05     405
0.15    1133
0.35    1282
0.60     835
0.85     345
Name: count, dtype: int64

In [66]:
dim_socios["churn_final"] = np.random.binomial(
    n=1,
    p=dim_socios["prob_churn"]
)

In [67]:
dim_socios["churn_final"].value_counts(normalize=True).round(3)

churn_final
0    0.632
1    0.368
Name: proportion, dtype: float64

Comprobamos que las probabilidades de riesgo están bien

In [69]:
dim_socios.groupby(
    "id_contrato"
)["churn_final"].mean().round(3)

id_contrato
1    0.440
2    0.268
3    0.193
Name: churn_final, dtype: float64

In [70]:
dim_socios.groupby(
    "vive_cerca"
)["churn_final"].mean().round(3)

vive_cerca
0    0.550
1    0.279
Name: churn_final, dtype: float64

In [71]:
dim_socios.groupby(
    "tiene_pareja_socio"
)["churn_final"].mean().round(3)

tiene_pareja_socio
0    0.381
1    0.248
Name: churn_final, dtype: float64

#Generamos fecha BAJA#

In [72]:
def generar_meses_activo(row):

    if row["churn_final"] == 0:
        return np.nan

    contrato = row["id_contrato"]

    if contrato == 1:  # mensual

        return np.random.choice(
            [1, 2, 3, 4, 5, 6, 9, 12],
            p=[0.10, 0.15, 0.20, 0.20,
               0.15, 0.10, 0.07, 0.03]
        )

    elif contrato == 2:  # semestral

        return np.random.choice(
            [3, 6, 9, 12, 18, 24],
            p=[0.10, 0.25, 0.20,
               0.20, 0.15, 0.10]
        )

    else:  # anual

        return np.random.choice(
            [12, 18, 24, 30, 36],
            p=[0.25, 0.25, 0.25,
               0.15, 0.10]
        )


dim_socios["meses_activo"] = dim_socios.apply(
    generar_meses_activo,
    axis=1
)

In [73]:
dim_socios.groupby(
    "id_contrato"
)["meses_activo"].mean().round(1)

id_contrato
1     4.2
2    10.9
3    21.9
Name: meses_activo, dtype: float64

In [74]:
#Fecha baja
def calcular_fecha_baja(row):

    if row["churn_final"] == 0:
        return pd.NaT

    fecha_baja = (
        row["fecha_alta"]
        + pd.DateOffset(months=int(row["meses_activo"]))
    )

    if fecha_baja > pd.Timestamp(FECHA_FIN):
        return pd.NaT

    return fecha_baja


dim_socios["fecha_baja"] = dim_socios.apply(
    calcular_fecha_baja,
    axis=1
)

In [75]:
dim_socios[
    [
        "id_socio",
        "fecha_alta",
        "meses_activo",
        "fecha_baja",
        "churn_final"
    ]
].head(10)

   id_socio fecha_alta  meses_activo fecha_baja  churn_final
0         1 2024-01-21           NaN        NaT            0
1         2 2025-05-02           NaN        NaT            0
2         3 2024-01-06           NaN        NaT            0
3         4 2025-02-28           NaN        NaT            0
4         5 2023-01-07           NaN        NaT            0
5         6 2024-02-18           NaN        NaT            0
6         7 2023-04-13           9.0 2024-01-13            1
7         8 2025-11-13           NaN        NaT            0
8         9 2023-10-16           6.0 2024-04-16            1
9        10 2025-01-07           NaN        NaT            0

In [76]:
dim_socios["fecha_baja"].isna().sum()

np.int64(2811)

In [77]:
(
    dim_socios["fecha_baja"] <
    dim_socios["fecha_alta"]
).sum()

np.int64(0)

In [78]:
# Saber cuantos tienen abandono pero no fecha de baja.
(
    (dim_socios["churn_final"] == 1)
    &
    (dim_socios["fecha_baja"].isna())
).sum()

np.int64(253)

In [79]:
dim_socios["churn_final"] = (
    dim_socios["fecha_baja"]
    .notna()
    .astype(int)
)

In [80]:
dim_socios["churn_final"].value_counts(normalize=True).round(3)

churn_final
0    0.703
1    0.297
Name: proportion, dtype: float64

FACT, VISITAS

In [81]:
def visitas_base_mes():

    return np.random.choice(
        [4, 6, 8, 10, 12, 14, 16, 18],
        p=[0.05, 0.10, 0.15, 0.25,
           0.20, 0.15, 0.07, 0.03]
    )

In [82]:
for _ in range(10):
    print(visitas_base_mes())

8
6
8
8
12
8
12
6
8
14

In [83]:
#visitas_mes_socio
def calcular_visitas_mes(
    visitas_base,
    churn_final,
    meses_hasta_baja
):

    visitas = visitas_base

    if churn_final == 1:

        if meses_hasta_baja <= 1:
            visitas *= 0.20

        elif meses_hasta_baja <= 2:
            visitas *= 0.40

        elif meses_hasta_baja <= 3:
            visitas *= 0.60

        elif meses_hasta_baja <= 4:
            visitas *= 0.80

    return max(0, round(visitas))

In [84]:
for meses in [6, 4, 3, 2, 1]:
    print(
        meses,
        calcular_visitas_mes(
            visitas_base=12,
            churn_final=1,
            meses_hasta_baja=meses
        )
    )

6 12
4 10
3 7
2 5
1 2

In [91]:
## Tabla Temporal mensual para cada socio
registros_socio_mes = []

for _, socio in dim_socios.iterrows():

    fecha_inicio = socio["fecha_alta"]
    fecha_fin = socio["fecha_baja"] if pd.notna(socio["fecha_baja"]) else pd.Timestamp(FECHA_FIN)

    meses = pd.period_range(
        start=fecha_inicio.to_period("M"),
        end=fecha_fin.to_period("M"),
        freq="M"
    )

    visitas_base = visitas_base_mes()

    for mes_periodo in meses:

        mes = mes_periodo.to_timestamp()

        meses_hasta_baja = 999

        if pd.notna(socio["fecha_baja"]):
            meses_hasta_baja = (
                (socio["fecha_baja"].year - mes.year) * 12
                + (socio["fecha_baja"].month - mes.month)
            )

        visitas_mes = calcular_visitas_mes(
            visitas_base=visitas_base,
            churn_final=socio["churn_final"],
            meses_hasta_baja=meses_hasta_baja
        )

        registros_socio_mes.append({
            "id_socio": socio["id_socio"],
            "id_centro": socio["id_centro"],
            "mes": mes,
            "visitas_mes": visitas_mes
        })

fact_socio_mes_temp = pd.DataFrame(registros_socio_mes)

fact_socio_mes_temp.head()

   id_socio  id_centro        mes  visitas_mes
0         1          1 2024-01-01           16
1         1          1 2024-02-01           16
2         1          1 2024-03-01           16
3         1          1 2024-04-01           16
4         1          1 2024-05-01           16

In [86]:
fact_socio_mes_temp.shape

(54554, 4)

In [92]:
# Validación de tabla temporal si tiene lógica
fact_socio_mes_temp["visitas_mes"].describe().round(1)

count    58425.0
mean        10.0
std          3.8
min          1.0
25%          8.0
50%         10.0
75%         12.0
max         18.0
Name: visitas_mes, dtype: float64

In [93]:
fact_socio_mes_temp.groupby("id_socio")["visitas_mes"].mean().describe().round(1)

count    4000.0
mean        9.0
std         4.0
min         1.0
25%         6.0
50%        10.0
75%        12.0
max        18.0
Name: visitas_mes, dtype: float64

In [95]:
#Comprobación de datos
fact_socio_mes_temp["id_socio"].nunique()

4000

Convertimos fact_socio_mes_temp en fact_visitas

In [96]:
def generar_hora_entrada():
    return np.random.choice(
        ["07:00", "08:00", "09:00", "13:00", "14:00", "18:00", "19:00", "20:00"],
        p=[0.08, 0.10, 0.07, 0.08, 0.07, 0.25, 0.22, 0.13]
    )


def generar_duracion():
    duracion = np.random.normal(loc=65, scale=20)
    return int(np.clip(round(duracion), 20, 180))


def generar_tipo_actividad():
    return np.random.choice(
        ["sala_libre", "cardio", "clase_grupal"],
        p=[0.60, 0.25, 0.15]
    )

In [97]:
visitas = []
id_visita = 1

for _, fila in fact_socio_mes_temp.iterrows():

    n_visitas = int(fila["visitas_mes"])
    
    for _ in range(n_visitas):
        
        dia = np.random.randint(1, 29)
        fecha_visita = pd.Timestamp(
            year=fila["mes"].year,
            month=fila["mes"].month,
            day=dia
        )
        
        id_fecha = int(fecha_visita.strftime("%Y%m%d"))
        
        visitas.append({
            "id_visita": id_visita,
            "id_socio": fila["id_socio"],
            "id_centro": fila["id_centro"],
            "id_fecha": id_fecha,
            "fecha_visita": fecha_visita,
            "hora_entrada": generar_hora_entrada(),
            "duracion_minutos": generar_duracion(),
            "tipo_actividad": generar_tipo_actividad()
        })
        
        id_visita += 1

fact_visitas = pd.DataFrame(visitas)

fact_visitas.head()

,id_visita,id_socio,id_centro,id_fecha,fecha_visita,hora_entrada,duracion_minutos,tipo_actividad
0,1,1,1,20240101,2024-01-01,19:00,69,sala_libre
1,2,1,1,20240113,2024-01-13,18:00,43,sala_libre
2,3,1,1,20240121,2024-01-21,19:00,91,sala_libre
3,4,1,1,20240101,2024-01-01,14:00,85,sala_libre
4,5,1,1,20240104,2024-01-04,13:00,88,sala_libre

In [98]:
fact_visitas.shape

(585797, 8)

In [99]:
fact_visitas = fact_visitas.merge(
    dim_socios[
        ["id_socio", "fecha_alta"]
    ],
    on="id_socio",
    how="left"
)

In [100]:
(
    fact_visitas["fecha_visita"]
    <
    fact_visitas["fecha_alta"]
).sum()

np.int64(19372)

In [101]:
fact_visitas = fact_visitas[
    fact_visitas["fecha_visita"] >= fact_visitas["fecha_alta"]
].copy()

In [102]:
(
    fact_visitas["fecha_visita"]
    <
    fact_visitas["fecha_alta"]
).sum()

np.int64(0)

In [103]:
fact_visitas = fact_visitas.drop(columns=["fecha_alta"])

In [104]:
fact_visitas.shape

(566425, 8)